force-app/main/default/objects/Individual__c/Individual__c.object-meta.xml
<CustomObject>
    <label>Individual</label>
    <nameField>
        <label>Individual Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individuals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Individual__c/fields/Geo__c.field-meta.xml
<CustomField>
    <fullName>Geo__c</fullName>
    <label>Geo</label>
    <scale>15</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Individual__c/fields/Is_Notification_Sent__c.field-meta.xml
<CustomField>
    <fullName>Is_Notification_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notification Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Individual__c/fields/Nearest_Vaccination_Center__c.field-meta.xml
<CustomField>
    <fullName>Nearest_Vaccination_Center__c</fullName>
    <label>Nearest Vaccination Center</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vaccination_Center__c/Vaccination_Center__c.object-meta.xml
<CustomObject>
    <label>Vaccination Center</label>
    <nameField>
        <label>Vaccination Center Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vaccination Centers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vaccination_Center__c/fields/Geo__c.field-meta.xml
<CustomField>
    <fullName>Geo__c</fullName>
    <label>Geo</label>
    <scale>5</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/classes/IndividualDataController.cls
public with sharing class IndividualDataController {
    public IndividualDataController() {

    }
    @AuraEnabled( cacheable = true )
    public static List< Individual__c > fetchIndividuals() {
     
        return [ SELECT Id, Name, Age__c, Email__c,Geo__Latitude__s,Is_Notification_Sent__c,Nearest_Vaccination_Center__c  FROM Individual__c ORDER BY Age__c DESC];
         
    }

    @AuraEnabled
    public static boolean sendEmailNotification(String recordId) {
        
        Boolean notification = false;
        Individual__c  indObj= [ SELECT Id,Is_Notification_Sent__c   FROM Individual__c where id=:recordId];        
        if(indObj!=Null){
            indObj.Is_Notification_Sent__c= true;
            notification=true;     
        } 
        try{
          update indObj;
      }
      catch (Exception ex){
        System.debug('There is an exception' + ex.getMessage());
      }
      return notification;
    }

    @AuraEnabled
    public static String findvacinationCenter(String recordId) {
        Individual__c  indObj = [SELECT Id, Name, Age__c, Email__c,Geo__Latitude__s,Geo__Longitude__s,Nearest_Vaccination_Center__c
        FROM Individual__c where id=:recordId];
        String nearersVacCenter = '';
        Decimal indiLatitide = indObj.Geo__Latitude__s;
        Decimal indiLongitude = indObj.Geo__Longitude__s;       
        List<Vaccination_Center__c> vacList = [SELECT id,Name,Geo__c,Geo__Latitude__s,Geo__Longitude__s from Vaccination_Center__c where 
                                    DISTANCE(Geo__c, GEOLOCATION( :indiLatitide, :indiLongitude), 'mi') > 20
                                     ORDER BY DISTANCE(Geo__c, GEOLOCATION( :indiLatitide, :indiLongitude ) , 'mi') ASC];
                                     System.debug('vacList ' + vacList.size());
        if(vacList.size()>0){
            nearersVacCenter = vacList[0].Name;
            indObj.Nearest_Vaccination_Center__c = nearersVacCenter;
            try{
                update indObj;
            }
            catch (Exception e){
                System.debug('There is an exception' + e.getMessage());
              }
        }
        else{
            nearersVacCenter = 'vacList[0].Name';
            System.debug('No neasrest vac center found ' + nearersVacCenter) ;
        }
        return nearersVacCenter;
    }

}